version: '3'

services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000

  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081    

  tomcat:
    build: 
      context: .
      dockerfile: Tomcat_Dockerfile
    ports:
      - 8080:8080

  