version: '3.3'

services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
  tomcat:
    build: 
      context: .
      dockerfile: Tomcat_Dockerfile
    ports:
      - 8090:8080
    volumes:
      - /home/senthil/Documents/temp:/usr/local/tomcat/webapps      
